'use strict'; // code generated by pbf v3.2.0

// BlockRecords ========================================

var BlockRecords = exports.BlockRecords = {};

BlockRecords.read = function (pbf, end) {
    return pbf.readFields(BlockRecords._readField, {blocks: []}, end);
};
BlockRecords._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.blocks.push(BlockRecords.BlockRecord.read(pbf, pbf.readVarint() + pbf.pos));
};
BlockRecords.write = function (obj, pbf) {
    if (obj.blocks) for (var i = 0; i < obj.blocks.length; i++) pbf.writeMessage(1, BlockRecords.BlockRecord.write, obj.blocks[i]);
};

// BlockRecords.BlockRecord ========================================

BlockRecords.BlockRecord = {};

BlockRecords.BlockRecord.read = function (pbf, end) {
    return pbf.readFields(BlockRecords.BlockRecord._readField, {geoId: "", population: 0, housingUnits: null, race: null, age: null}, end);
};
BlockRecords.BlockRecord._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.geoId = pbf.readString();
    else if (tag === 2) obj.population = pbf.readVarint(true);
    else if (tag === 3) obj.housingUnits = BlockRecords.BlockRecord.HousingUnits.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.race = BlockRecords.BlockRecord.Race.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 5) obj.age = BlockRecords.BlockRecord.Age.read(pbf, pbf.readVarint() + pbf.pos);
};
BlockRecords.BlockRecord.write = function (obj, pbf) {
    if (obj.geoId) pbf.writeStringField(1, obj.geoId);
    if (obj.population) pbf.writeVarintField(2, obj.population);
    if (obj.housingUnits) pbf.writeMessage(3, BlockRecords.BlockRecord.HousingUnits.write, obj.housingUnits);
    if (obj.race) pbf.writeMessage(4, BlockRecords.BlockRecord.Race.write, obj.race);
    if (obj.age) pbf.writeMessage(5, BlockRecords.BlockRecord.Age.write, obj.age);
};

// BlockRecords.BlockRecord.HousingUnits ========================================

BlockRecords.BlockRecord.HousingUnits = {};

BlockRecords.BlockRecord.HousingUnits.read = function (pbf, end) {
    return pbf.readFields(BlockRecords.BlockRecord.HousingUnits._readField, {total: 0, occupied: 0, vacant: 0}, end);
};
BlockRecords.BlockRecord.HousingUnits._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.total = pbf.readVarint(true);
    else if (tag === 2) obj.occupied = pbf.readVarint(true);
    else if (tag === 3) obj.vacant = pbf.readVarint(true);
};
BlockRecords.BlockRecord.HousingUnits.write = function (obj, pbf) {
    if (obj.total) pbf.writeVarintField(1, obj.total);
    if (obj.occupied) pbf.writeVarintField(2, obj.occupied);
    if (obj.vacant) pbf.writeVarintField(3, obj.vacant);
};

// BlockRecords.BlockRecord.Race ========================================

BlockRecords.BlockRecord.Race = {};

BlockRecords.BlockRecord.Race.read = function (pbf, end) {
    return pbf.readFields(BlockRecords.BlockRecord.Race._readField, {total: 0, white: 0, black: 0, asian: 0, native: 0, other: 0, hispanic: 0}, end);
};
BlockRecords.BlockRecord.Race._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.total = pbf.readVarint(true);
    else if (tag === 2) obj.white = pbf.readVarint(true);
    else if (tag === 3) obj.black = pbf.readVarint(true);
    else if (tag === 4) obj.asian = pbf.readVarint(true);
    else if (tag === 5) obj.native = pbf.readVarint(true);
    else if (tag === 6) obj.other = pbf.readVarint(true);
    else if (tag === 7) obj.hispanic = pbf.readVarint(true);
};
BlockRecords.BlockRecord.Race.write = function (obj, pbf) {
    if (obj.total) pbf.writeVarintField(1, obj.total);
    if (obj.white) pbf.writeVarintField(2, obj.white);
    if (obj.black) pbf.writeVarintField(3, obj.black);
    if (obj.asian) pbf.writeVarintField(4, obj.asian);
    if (obj.native) pbf.writeVarintField(5, obj.native);
    if (obj.other) pbf.writeVarintField(6, obj.other);
    if (obj.hispanic) pbf.writeVarintField(7, obj.hispanic);
};

// BlockRecords.BlockRecord.Age ========================================

BlockRecords.BlockRecord.Age = {};

BlockRecords.BlockRecord.Age.read = function (pbf, end) {
    return pbf.readFields(BlockRecords.BlockRecord.Age._readField, {u10: 0, u18: 0, u30: 0, u65: 0, over65: 0}, end);
};
BlockRecords.BlockRecord.Age._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.u10 = pbf.readVarint(true);
    else if (tag === 2) obj.u18 = pbf.readVarint(true);
    else if (tag === 3) obj.u30 = pbf.readVarint(true);
    else if (tag === 4) obj.u65 = pbf.readVarint(true);
    else if (tag === 5) obj.over65 = pbf.readVarint(true);
};
BlockRecords.BlockRecord.Age.write = function (obj, pbf) {
    if (obj.u10) pbf.writeVarintField(1, obj.u10);
    if (obj.u18) pbf.writeVarintField(2, obj.u18);
    if (obj.u30) pbf.writeVarintField(3, obj.u30);
    if (obj.u65) pbf.writeVarintField(4, obj.u65);
    if (obj.over65) pbf.writeVarintField(5, obj.over65);
};
