'use strict'; // code generated by pbf v3.2.0

// LodesRecords ========================================

var LodesRecords = exports.LodesRecords = {};

LodesRecords.read = function (pbf, end) {
    return pbf.readFields(LodesRecords._readField, {blocks: []}, end);
};
LodesRecords._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.blocks.push(LodesRecords.LodesRecord.read(pbf, pbf.readVarint() + pbf.pos));
};
LodesRecords.write = function (obj, pbf) {
    if (obj.blocks) for (var i = 0; i < obj.blocks.length; i++) pbf.writeMessage(1, LodesRecords.LodesRecord.write, obj.blocks[i]);
};

// LodesRecords.LodesRecord ========================================

LodesRecords.LodesRecord = {};

LodesRecords.LodesRecord.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord._readField, {geoId: "", jobs: 0, age: null, income: null, naics: null, race: null, ethnicity: null, education: null, sex: null, firmAge: null, firmSize: null}, end);
};
LodesRecords.LodesRecord._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.geoId = pbf.readString();
    else if (tag === 2) obj.jobs = pbf.readVarint(true);
    else if (tag === 3) obj.age = LodesRecords.LodesRecord.Age.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.income = LodesRecords.LodesRecord.Income.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 5) obj.naics = LodesRecords.LodesRecord.Naics.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 6) obj.race = LodesRecords.LodesRecord.Race.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 7) obj.ethnicity = LodesRecords.LodesRecord.Ethnicity.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 8) obj.education = LodesRecords.LodesRecord.Education.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 9) obj.sex = LodesRecords.LodesRecord.Sex.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 10) obj.firmAge = LodesRecords.LodesRecord.FirmAge.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 11) obj.firmSize = LodesRecords.LodesRecord.FirmSize.read(pbf, pbf.readVarint() + pbf.pos);
};
LodesRecords.LodesRecord.write = function (obj, pbf) {
    if (obj.geoId) pbf.writeStringField(1, obj.geoId);
    if (obj.jobs) pbf.writeVarintField(2, obj.jobs);
    if (obj.age) pbf.writeMessage(3, LodesRecords.LodesRecord.Age.write, obj.age);
    if (obj.income) pbf.writeMessage(4, LodesRecords.LodesRecord.Income.write, obj.income);
    if (obj.naics) pbf.writeMessage(5, LodesRecords.LodesRecord.Naics.write, obj.naics);
    if (obj.race) pbf.writeMessage(6, LodesRecords.LodesRecord.Race.write, obj.race);
    if (obj.ethnicity) pbf.writeMessage(7, LodesRecords.LodesRecord.Ethnicity.write, obj.ethnicity);
    if (obj.education) pbf.writeMessage(8, LodesRecords.LodesRecord.Education.write, obj.education);
    if (obj.sex) pbf.writeMessage(9, LodesRecords.LodesRecord.Sex.write, obj.sex);
    if (obj.firmAge) pbf.writeMessage(10, LodesRecords.LodesRecord.FirmAge.write, obj.firmAge);
    if (obj.firmSize) pbf.writeMessage(11, LodesRecords.LodesRecord.FirmSize.write, obj.firmSize);
};

// LodesRecords.LodesRecord.Age ========================================

LodesRecords.LodesRecord.Age = {};

LodesRecords.LodesRecord.Age.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Age._readField, {u30: 0, u55: 0, o55: 0}, end);
};
LodesRecords.LodesRecord.Age._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.u30 = pbf.readVarint(true);
    else if (tag === 2) obj.u55 = pbf.readVarint(true);
    else if (tag === 3) obj.o55 = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Age.write = function (obj, pbf) {
    if (obj.u30) pbf.writeVarintField(1, obj.u30);
    if (obj.u55) pbf.writeVarintField(2, obj.u55);
    if (obj.o55) pbf.writeVarintField(3, obj.o55);
};

// LodesRecords.LodesRecord.Income ========================================

LodesRecords.LodesRecord.Income = {};

LodesRecords.LodesRecord.Income.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Income._readField, {u1250: 0, u3333: 0, o3333: 0}, end);
};
LodesRecords.LodesRecord.Income._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.u1250 = pbf.readVarint(true);
    else if (tag === 2) obj.u3333 = pbf.readVarint(true);
    else if (tag === 3) obj.o3333 = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Income.write = function (obj, pbf) {
    if (obj.u1250) pbf.writeVarintField(1, obj.u1250);
    if (obj.u3333) pbf.writeVarintField(2, obj.u3333);
    if (obj.o3333) pbf.writeVarintField(3, obj.o3333);
};

// LodesRecords.LodesRecord.Naics ========================================

LodesRecords.LodesRecord.Naics = {};

LodesRecords.LodesRecord.Naics.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Naics._readField, {ag: 0, min: 0, util: 0, cons: 0, mfg: 0, whole: 0, retail: 0, trans: 0, info: 0, fin: 0, re: 0, tech: 0, mgmt: 0, waste: 0, ed: 0, health: 0, rec: 0, food: 0, other: 0, pa: 0}, end);
};
LodesRecords.LodesRecord.Naics._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.ag = pbf.readVarint(true);
    else if (tag === 2) obj.min = pbf.readVarint(true);
    else if (tag === 3) obj.util = pbf.readVarint(true);
    else if (tag === 4) obj.cons = pbf.readVarint(true);
    else if (tag === 5) obj.mfg = pbf.readVarint(true);
    else if (tag === 6) obj.whole = pbf.readVarint(true);
    else if (tag === 7) obj.retail = pbf.readVarint(true);
    else if (tag === 8) obj.trans = pbf.readVarint(true);
    else if (tag === 9) obj.info = pbf.readVarint(true);
    else if (tag === 10) obj.fin = pbf.readVarint(true);
    else if (tag === 11) obj.re = pbf.readVarint(true);
    else if (tag === 12) obj.tech = pbf.readVarint(true);
    else if (tag === 13) obj.mgmt = pbf.readVarint(true);
    else if (tag === 14) obj.waste = pbf.readVarint(true);
    else if (tag === 15) obj.ed = pbf.readVarint(true);
    else if (tag === 16) obj.health = pbf.readVarint(true);
    else if (tag === 17) obj.rec = pbf.readVarint(true);
    else if (tag === 18) obj.food = pbf.readVarint(true);
    else if (tag === 19) obj.other = pbf.readVarint(true);
    else if (tag === 20) obj.pa = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Naics.write = function (obj, pbf) {
    if (obj.ag) pbf.writeVarintField(1, obj.ag);
    if (obj.min) pbf.writeVarintField(2, obj.min);
    if (obj.util) pbf.writeVarintField(3, obj.util);
    if (obj.cons) pbf.writeVarintField(4, obj.cons);
    if (obj.mfg) pbf.writeVarintField(5, obj.mfg);
    if (obj.whole) pbf.writeVarintField(6, obj.whole);
    if (obj.retail) pbf.writeVarintField(7, obj.retail);
    if (obj.trans) pbf.writeVarintField(8, obj.trans);
    if (obj.info) pbf.writeVarintField(9, obj.info);
    if (obj.fin) pbf.writeVarintField(10, obj.fin);
    if (obj.re) pbf.writeVarintField(11, obj.re);
    if (obj.tech) pbf.writeVarintField(12, obj.tech);
    if (obj.mgmt) pbf.writeVarintField(13, obj.mgmt);
    if (obj.waste) pbf.writeVarintField(14, obj.waste);
    if (obj.ed) pbf.writeVarintField(15, obj.ed);
    if (obj.health) pbf.writeVarintField(16, obj.health);
    if (obj.rec) pbf.writeVarintField(17, obj.rec);
    if (obj.food) pbf.writeVarintField(18, obj.food);
    if (obj.other) pbf.writeVarintField(19, obj.other);
    if (obj.pa) pbf.writeVarintField(20, obj.pa);
};

// LodesRecords.LodesRecord.Race ========================================

LodesRecords.LodesRecord.Race = {};

LodesRecords.LodesRecord.Race.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Race._readField, {white: 0, black: 0, native: 0, asian: 0, pacific: 0, twoOrMore: 0}, end);
};
LodesRecords.LodesRecord.Race._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.white = pbf.readVarint(true);
    else if (tag === 2) obj.black = pbf.readVarint(true);
    else if (tag === 3) obj.native = pbf.readVarint(true);
    else if (tag === 4) obj.asian = pbf.readVarint(true);
    else if (tag === 5) obj.pacific = pbf.readVarint(true);
    else if (tag === 6) obj.twoOrMore = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Race.write = function (obj, pbf) {
    if (obj.white) pbf.writeVarintField(1, obj.white);
    if (obj.black) pbf.writeVarintField(2, obj.black);
    if (obj.native) pbf.writeVarintField(3, obj.native);
    if (obj.asian) pbf.writeVarintField(4, obj.asian);
    if (obj.pacific) pbf.writeVarintField(5, obj.pacific);
    if (obj.twoOrMore) pbf.writeVarintField(6, obj.twoOrMore);
};

// LodesRecords.LodesRecord.Ethnicity ========================================

LodesRecords.LodesRecord.Ethnicity = {};

LodesRecords.LodesRecord.Ethnicity.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Ethnicity._readField, {nonHispanic: 0, hispanic: 0}, end);
};
LodesRecords.LodesRecord.Ethnicity._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.nonHispanic = pbf.readVarint(true);
    else if (tag === 2) obj.hispanic = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Ethnicity.write = function (obj, pbf) {
    if (obj.nonHispanic) pbf.writeVarintField(1, obj.nonHispanic);
    if (obj.hispanic) pbf.writeVarintField(2, obj.hispanic);
};

// LodesRecords.LodesRecord.Education ========================================

LodesRecords.LodesRecord.Education = {};

LodesRecords.LodesRecord.Education.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Education._readField, {ltHs: 0, hs: 0, coll: 0, ba: 0}, end);
};
LodesRecords.LodesRecord.Education._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.ltHs = pbf.readVarint(true);
    else if (tag === 2) obj.hs = pbf.readVarint(true);
    else if (tag === 3) obj.coll = pbf.readVarint(true);
    else if (tag === 4) obj.ba = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Education.write = function (obj, pbf) {
    if (obj.ltHs) pbf.writeVarintField(1, obj.ltHs);
    if (obj.hs) pbf.writeVarintField(2, obj.hs);
    if (obj.coll) pbf.writeVarintField(3, obj.coll);
    if (obj.ba) pbf.writeVarintField(4, obj.ba);
};

// LodesRecords.LodesRecord.Sex ========================================

LodesRecords.LodesRecord.Sex = {};

LodesRecords.LodesRecord.Sex.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.Sex._readField, {m: 0, f: 0}, end);
};
LodesRecords.LodesRecord.Sex._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.m = pbf.readVarint(true);
    else if (tag === 2) obj.f = pbf.readVarint(true);
};
LodesRecords.LodesRecord.Sex.write = function (obj, pbf) {
    if (obj.m) pbf.writeVarintField(1, obj.m);
    if (obj.f) pbf.writeVarintField(2, obj.f);
};

// LodesRecords.LodesRecord.FirmAge ========================================

LodesRecords.LodesRecord.FirmAge = {};

LodesRecords.LodesRecord.FirmAge.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.FirmAge._readField, {u2: 0, u4: 0, u6: 0, u11: 0, g11: 0}, end);
};
LodesRecords.LodesRecord.FirmAge._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.u2 = pbf.readVarint(true);
    else if (tag === 2) obj.u4 = pbf.readVarint(true);
    else if (tag === 3) obj.u6 = pbf.readVarint(true);
    else if (tag === 4) obj.u11 = pbf.readVarint(true);
    else if (tag === 5) obj.g11 = pbf.readVarint(true);
};
LodesRecords.LodesRecord.FirmAge.write = function (obj, pbf) {
    if (obj.u2) pbf.writeVarintField(1, obj.u2);
    if (obj.u4) pbf.writeVarintField(2, obj.u4);
    if (obj.u6) pbf.writeVarintField(3, obj.u6);
    if (obj.u11) pbf.writeVarintField(4, obj.u11);
    if (obj.g11) pbf.writeVarintField(5, obj.g11);
};

// LodesRecords.LodesRecord.FirmSize ========================================

LodesRecords.LodesRecord.FirmSize = {};

LodesRecords.LodesRecord.FirmSize.read = function (pbf, end) {
    return pbf.readFields(LodesRecords.LodesRecord.FirmSize._readField, {u20: 0, u50: 0, u250: 0, u500: 0, g500: 0}, end);
};
LodesRecords.LodesRecord.FirmSize._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.u20 = pbf.readVarint(true);
    else if (tag === 2) obj.u50 = pbf.readVarint(true);
    else if (tag === 3) obj.u250 = pbf.readVarint(true);
    else if (tag === 4) obj.u500 = pbf.readVarint(true);
    else if (tag === 5) obj.g500 = pbf.readVarint(true);
};
LodesRecords.LodesRecord.FirmSize.write = function (obj, pbf) {
    if (obj.u20) pbf.writeVarintField(1, obj.u20);
    if (obj.u50) pbf.writeVarintField(2, obj.u50);
    if (obj.u250) pbf.writeVarintField(3, obj.u250);
    if (obj.u500) pbf.writeVarintField(4, obj.u500);
    if (obj.g500) pbf.writeVarintField(5, obj.g500);
};
